// front/admin/src/views/auth/login/index.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useUserStore } from '@/stores/userstore';
import type { loginDto } from '@/dto/userDto';
const userstore = useUserStore()

const loginInfo = ref({
    loginId: '',
    password: ''
})

const onFinish = (loginInfo: loginDto) => {
    userstore.getUserInfo(loginInfo)
}
</script>

<template>
    <div class="flex justify-center items-center h-screen">
        <div
            class="flex flex-col bg-gradient-to-r from-transblue via-white to-transpink items-center rounded-3xl shadow-lg">
            <div class="flex flex-row p-2 ">
                <div class="flex w-1/2 justify-center items-center">
                    <div class="font-bold text-2xl text-center">鸭鸭活动管理</div>
                </div>
                <div class="w-1/2 flex flex-col justify-center m-4 p-4">
                    <a-form layout="vertical" :model="loginInfo" name="basic" autocomplete="off" @finish="onFinish">
                        <a-form-item label="用户id" name="loginId" :rules="[{ required: true, message: '请输入用户登录id' }]">
                            <a-input v-model:value="loginInfo.loginId" />
                        </a-form-item>

                        <a-form-item label="密码" name="password" :rules="[{ required: true, message: '请输入密码' }]">
                            <a-input-password v-model:value="loginInfo.password" />
                        </a-form-item>

                        <a-form-item class="flex justify-center">
                            <a-button type="primary" html-type="submit">登录</a-button>
                        </a-form-item>
                    </a-form>
                </div>
            </div>
            <div class="m-2 font-bold">还未注册?<a class="text-blue-300" href="/auth/register">点击注册</a></div>
        </div>
    </div>
</template>

// front/user/src/pages/login/index.tsx
import { Button, Form, Input, Radio } from "antd";
import { LockOutlined, UserOutlined } from "@ant-design/icons";
import useLogin from "../../hooks/login/uselogin";
export default function Login() {
  const { onFinish } = useLogin();
  return (
    <div className="flex flex-col md:flex-row justify-center items-center h-screen mx-6">
      <div className="flex flex-col justify-center items-center rounded-2xl shadow-lg w-full h-1/2 md:w-1/2 bg-gradient-to-r from-transblue via-white to-transpink">
        <div className="flex flex-col h-full w-full m-2">
          <div className="text-center text-2xl font-bold m-2">
            欢迎来到活动报名网站
          </div>
          <Form
            layout="vertical"
            onFinish={onFinish}
            className="m-2 p-2 justify-center items-center"
          >
            <Form.Item
              label="登录ID"
              name="loginId"
              rules={[
                {
                  required: true,
                  message: "登录ID为必填项",
                },
              ]}
            >
              <Input prefix={<UserOutlined />} placeholder="请输入登录ID" />
            </Form.Item>
            <Form.Item
              label="密码"
              name="password"
              rules={[
                {
                  required: true,
                  message: "密码为必填项",
                },
              ]}
              hasFeedback
            >
              <Input.Password
                prefix={<LockOutlined />}
                type="password"
                placeholder="请输入密码"
              />
            </Form.Item>
            <Form.Item className="flex justify-center">
              <Button type="primary" htmlType="submit" className="w-28">
                登录
              </Button>
            </Form.Item>
          </Form>
          <div className="text-center text-sm">
            没有账号？
            <a className="text-blue-500" href="/register">
              点击注册
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}
